# Generated by Django 4.0.3 on 2022-03-16 08:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='название')),
            ],
            options={
                'verbose_name': 'аллерген',
                'verbose_name_plural': 'аллергены',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='название')),
                ('allergen', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodplan_app.allergen')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='изображение')),
                ('meal', models.CharField(choices=[('breakfast', 'завтрак'), ('lunch', 'обед'), ('dinner', 'ужин'), ('dessert', 'десерт'), ('new_year', 'новогодний')], max_length=50, verbose_name='прием пищи')),
                ('menu_type', models.CharField(choices=[('classic', 'классическое'), ('low_carb', 'низкоуглеводное'), ('vegetarian', 'вегетарианское'), ('keto', 'кето')], max_length=50, verbose_name='тип меню')),
            ],
            options={
                'verbose_name': 'рецепт',
                'verbose_name_plural': 'рецепты',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_type', models.CharField(choices=[('classic', 'классическое'), ('low_carb', 'низкоуглеводное'), ('vegetarian', 'вегетарианское'), ('keto', 'кето')], max_length=50, verbose_name='тип меню')),
                ('persons_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='количество персон')),
                ('months_count', models.IntegerField(choices=[(12, 'год'), (3, 'три месяца')], verbose_name='количество месяцев подписки')),
                ('last_payed_at', models.DateField(verbose_name='дата последней оплаты')),
                ('current_receipt', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodplan_app.receipt', verbose_name='текущий рецепт')),
                ('excluded_allergens', models.ManyToManyField(related_name='excluded_subscriptions', to='foodplan_app.allergen', verbose_name='исключенные аллергены')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'подписка',
                'verbose_name_plural': 'подписки',
            },
        ),
        migrations.CreateModel(
            name='ReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=50, verbose_name='количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts_items', to='foodplan_app.product')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='foodplan_app.receipt')),
            ],
            options={
                'verbose_name': 'элемент рецепта',
                'verbose_name_plural': 'элементы рецепта',
            },
        ),
    ]
