# Generated by Django 4.0.3 on 2022-03-17 07:00

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='menu_type',
        ),
        migrations.AddField(
            model_name='subscription',
            name='meals',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('breakfast', 'завтрак'), ('lunch', 'обед'), ('dinner', 'ужин'), ('dessert', 'десерт'), ('new_year', 'новогодний')], default=(), max_length=39),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='excluded_allergens',
            field=models.ManyToManyField(blank=True, related_name='excluded_subscriptions', to='foodplan_app.allergen', verbose_name='исключенные аллергены'),
        ),
    ]
