# Generated by Django 4.0.3 on 2022-03-17 10:50

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan_app', '0002_remove_subscription_menu_type_subscription_meals_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='menu_type',
        ),
        migrations.AddField(
            model_name='receipt',
            name='menu_types',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('classic', 'классическое'), ('low_carb', 'низкоуглеводное'), ('vegetarian', 'вегетарианское'), ('keto', 'кето')], default=(), max_length=32, verbose_name='тип меню'),
        ),
    ]
