# Generated by Django 4.0.3 on 2022-03-17 11:16

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan_app', '0003_remove_receipt_menu_type_receipt_menu_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='meal',
        ),
        migrations.AddField(
            model_name='receipt',
            name='meals',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('breakfast', 'завтрак'), ('lunch', 'обед'), ('dinner', 'ужин'), ('dessert', 'десерт'), ('new_year', 'новогодний')], default=(), max_length=39, verbose_name='приемы пищи'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='menu_types',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('classic', 'классическое'), ('low_carb', 'низкоуглеводное'), ('vegetarian', 'вегетарианское'), ('keto', 'кето')], default=(), max_length=32, verbose_name='типы меню'),
        ),
    ]
