# Generated by Django 4.0.3 on 2022-03-17 11:23

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('foodplan_app', '0004_remove_receipt_meal_receipt_meals_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receipt',
            new_name='Recipe',
        ),
        migrations.RenameModel(
            old_name='ReceiptItem',
            new_name='RecipeItem',
        ),
        migrations.RenameField(
            model_name='recipeitem',
            old_name='receipt',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='current_receipt',
            new_name='current_recipe',
        ),
    ]
