# Generated by Django 4.0.3 on 2022-03-18 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodplan_app', '0005_rename_receipt_recipe_rename_receiptitem_recipeitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='source',
            field=models.URLField(blank=True, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='product',
            name='allergen',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodplan_app.allergen', verbose_name='аллерген'),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts_items', to='foodplan_app.product', verbose_name='продукт'),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='foodplan_app.recipe', verbose_name='рецепт'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
