# Generated by Django 4.0.3 on 2022-03-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan_app', '0007_recipe_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='menu_type',
            field=models.CharField(choices=[('classic', 'классическое'), ('low_carb', 'низкоуглеводное'), ('vegetarian', 'вегетарианское'), ('keto', 'кето')], default='classic', max_length=50, verbose_name='Тип меню'),
            preserve_default=False,
        ),
    ]
